print('q:1')
a=2.5
print(type(a))
print('q:2')
a=25.5
print(type(a))
print('q:3')
a='25'
print(type(a))
print('q:4')
age=21
print('q:5')
height=5.8
print('q:6')
name='Arun'
print('q:7')
age,price,name=20,99.5,'Ravi'
print('q:8')
marks=90
print(type(marks))
print('q:9')
temperature=36.5
print(type(temperature))
print('q:10')
message='Welcome'
print(type(message))

